cc_library(
    name = "interface",
    hdrs = ["include/reify/pure_cpp/object_visualizer.h"],
    includes = [
        "include",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@vulkan_sdk//:vulkan",
        "@reify//src/window",
        "//src/utils",
    ],
)
