cc_library(
    name = "core",
    srcs = [],
    hdrs = [
        "public_include/reify/pure_cpp/common_types.h",
    ],
    includes = [
        "public_include",
    ],
    visibility = ["//visibility:public"],
)
