@echo off
SETLOCAL EnableExtensions EnableDelayedExpansion

SET MANIFEST_FILE=%~f1
SET PACKAGE_DIR=%~f2
SET REMOVE_PREFIX=%3

echo MANIFEST FILE: "!MANIFEST_FILE!"
cat "!MANIFEST_FILE!"

for /F "tokens=1*" %%i in (%MANIFEST_FILE%) do (
  SET DESTINATION_RELATIVE_PATH_WITH_PREFIX=%%i
  SET SOURCE_FILEPATH_WITH_FORWARDSLASHES=%%j
  SET DESTINATION_RELATIVE_PATH=!DESTINATION_RELATIVE_PATH_WITH_PREFIX:%REMOVE_PREFIX%=!

  for %%F in ("!SOURCE_FILEPATH_WITH_FORWARDSLASHES!") do (
    SET SOURCE_FILEPATH=%%~fF
  )

  set TARGET_FILE=%PACKAGE_DIR%/!DESTINATION_RELATIVE_PATH!
  echo COPYING "!SOURCE_FILEPATH!" to "!TARGET_FILE!"
  echo F|xcopy /Y "!SOURCE_FILEPATH!" "!TARGET_FILE!"
)
