name:                reify-interface-builder

dependencies:
- base >= 4.7 && < 5
- filepath >= 1.4.0.0
- idt

executables:
  reify-interface-builder:
    main: Main.hs
    other-modules:
      - ReifyIdt
