name:                reify-interface-builder

default-extensions:
  - DeriveGeneric

dependencies:
- base >= 4.7 && < 5
- filepath >= 1.4.0.0
- aeson >= 1.4.0.0
- text >= 1.2.0.0
- idt
- reify-input-interface

executables:
  reify-interface-builder:
    main: Main.hs
  reify-interface-config-dump-json:
    main: DumpInterfaceConfigJSON.hs
