name:                reify-interface-builder

dependencies:
- base >= 4.7 && < 5
- idt


executables:
  reify-interface-builder-ts:
    main: TypeScriptMain.hs
    other-modules:
      - ReifyIdt
  reify-interface-builder-cpp-v8:
    main: CppV8Main.hs
    other-modules:
      - ReifyIdt