cc_library(
    name = "geometry",
    srcs = [
        "src/export_to_stl.cc",
    ],
    hdrs = [
        "include/hypo/geometry/export_to_stl.h",
        "include/hypo/geometry/triangle_soup.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//:hypo-purecpp",
        "@glm",
    ],
)
