name: Build

on: [push]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu, windows]
        include:
          - os: ubuntu
            runs-on: ubuntu-20.04
            build-script: ./build.sh
          - os: windows
            runs-on: windows-2019
            build-script: ./build.bat
    runs-on: ${{ matrix.runs-on }}
    env:
      build_artifact: hypo-x64-${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ${{ matrix.build-script }} ${{ env.build_artifact }}
      - name: Archive resulting executable
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.build_artifact }}
          path: ${{ env.build_artifact }}
          retention-days: 2

  # If a tag starting with "v" is pushed, assume it represents a release and
  # go ahead and create a draft release for this version of the code.
  create_release:
    name: Create release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-20.04
    steps:
      # First get the tag name without the "refs/tags/" part.
      - name: Get Tag Name
        id: tag_name
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      # Create the draft release, we'll add artifacts to it later.
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.tag_name.outputs.tag }}
          body: ENTER RELEASE NOTES HERE.
          draft: true
          prerelease: true  # I don't really know what this implies...
    outputs:
      tag: ${{ steps.tag_name.outputs.tag }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  # Now attach the build artifacts to the new release.
  upload_artifacts_to_release:
    name: Attach artifact to release
    needs: create_release
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ubuntu, windows]
        include:
          - os: ubuntu
            archive_command: tar -czvf
            archive_extension: tar.gz
            asset_content_type: application/gzip
          - os: windows
            archive_command: zip -r
            archive_extension: zip
            asset_content_type: application/zip
    env:
      build_artifact: hypo-x64-${{ matrix.os }}
      release_artifact: hypo-x64-${{ matrix.os }}-${{ needs.create_release.outputs.tag }}
      release_artifact_archive_filename: hypo-x64-${{ matrix.os }}-${{ needs.create_release.outputs.tag }}.${{ matrix.archive_extension }}
    steps:
      # Download build artifacts emitted from the build step.
      - uses: actions/download-artifact@v2
        with:
          name: ${{ env.build_artifact }}
          path: ./${{ env.release_artifact }}
      # Package up the artifacts into an archive native to the OS.
      - name: Package Artifacts
        run: ${{ matrix.archive_command }} ${{ env.release_artifact_archive_filename }} ${{ env.release_artifact }}
      # Finally upload the resulting archive packages to the draft release we
      # created a few steps ago.
      - name: Attach packaged artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./${{ env.release_artifact_archive_filename }}
          asset_name: ${{ env.release_artifact_archive_filename }}
          asset_content_type: ${{ matrix.asset_content_type }}
